### ISSUE TITLE
IK Relies on private moveit functions

### ISSUE THREAD

**Issue by bsaund** [UM-ARM-Lab/arm_robots#39]
The IK exposed in the jacobian follower relies on `setIkSolverFrame`, which will be made private in the next release of moveit.

**Comment by bsaund** [comment]
`setIkSolverFrame` is needed because the solver base frame is `victor_[right/left]_arm_link_0`. Looks like the solver was (reasonably) computed just for the robot arms and ignores the static base links.

`std::cout << "Sovler IK Frame: " << solver->getBaseFrame() << "\n";`
-> "Sovler IK Frame: victor_right_arm_link_0". 


One solution is recreate the logic of `setIkSolverFrame` in our own code :(

**Comment by bsaund** [comment]
I created a moveit issue requesting clarification: 
https://github.com/ros-planning/moveit/issues/2574

**Comment by bsaund** [comment]
moveit will revert, thus no change is needed from us: 
https://github.com/ros-planning/moveit/pull/2575

**Comment by PeterMitrano** [comment]
we need to do a rebase at some point

**Comment by bsaund** [comment]
I don't understand.
1) I'm currently on master. These changes are merged in
2) Is your comment related to this issue? I believe this issue is actually resolved

**Comment by PeterMitrano** [comment]
oh I was referring to our fork of moveit, which you're probably not using
