### ISSUE TITLE
Jacobian Follower: Robot is late in reaching goal

### ISSUE THREAD

**Issue by bsaund** [UM-ARM-Lab/arm_robots#70]
When running `victor.follow_jacobian_to_position(...)` twice in a row, the following error message appears repeatedly and victor fails to execute the second jacobian follow.

Repo steps:
Terminal 1: `roslaunch arm_robots rviz_victor.launch launch_fake_dual_arm_bridge:=true`
Terminal 2: `rviz -d [arm_robots]/rviz/victor.rviz
pycharm: `victor_basic_motion.py` or `jacobian_follwer_bug.py`. Bug appears after "Follow jacobian to pose 2?"

[WARN][/victor_basic_motion]: Robot is late in reaching goal. Error is:
victor_right_arm_joint_1: -0.05
victor_right_arm_joint_2: -0.15
victor_right_arm_joint_3: -0.05
victor_right_arm_joint_4: -0.10
victor_right_arm_joint_5: 0.05
victor_right_arm_joint_6: 0.10
victor_right_arm_joint_7: 0.01

Thoughts:
`victor.block = True`, however the blocking does not seems to be working. The bug disappears if you add a long enough `rospy.sleep(5)` between the follow_jacobian calls.
Perhaps this issue only appears when using fake victor, as fake victor immediately reaches any goal position. Untested.

**Comment by PeterMitrano** [comment]
I have no idea, I've never seen this nor run the jacobian follower with fake victor

**Comment by bsaund** [comment]
Seems to only be a problem with fake victor.
Using gazebo, I did not see this issue.
`roslaunch arm_robots victor.launch gazebo_world:="victor_empty" sim:=true`
